# docker-compose.yml — tuned for Apple-silicon Macs (M-series)
version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - sonardb:/var/lib/postgresql/data
    healthcheck:                     # wait-for-DB so SQ doesn’t crash-loop
      test: ["CMD-SHELL", "pg_isready -U sonar"]
      interval: 5s
      timeout: 3s
      retries: 10

  sonarqube:
    # verify the tag exists first: docker pull sonarqube:community
    image: sonarqube:community
    depends_on:
      db:
        condition: service_healthy
    ports: ["9000:9000"]
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ulimits:                        # Elasticsearch refuses to start without these
      nofile: 131072
      nproc: 8192
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

  mcp:
    image: mcp/sonarqube:latest
    depends_on:
      - sonarqube
    environment:
      STORAGE_PATH: /app/mcp-storage
      SONARQUBE_URL: http://sonarqube:9000
      SONARQUBE_TOKEN: ${SONAR_TOKEN}
    stdin_open: true
    tty: true
    restart: unless-stopped
    tmpfs:
      - /app/mcp-storage:rw,size=100M

volumes:
  sonardb:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
